'use client';

import { useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, Palette, RotateCcw } from 'lucide-react';
import { useWorkspace } from '@clayface/editor';
import { contrastRatio, designSystemSchema, type DesignSystem } from '@clayface/schema';
import { Button } from './ui';

export function DesignSystemWorkspace({ onApplied }: { onApplied: () => void }) {
  const { project, updateSystem } = useWorkspace();
  const [draft, setDraft] = useState<DesignSystem>(project.designSystem);
  const [tab, setTab] = useState('Foundations');
  const [error, setError] = useState('');
  const changed = JSON.stringify({ ...draft, version: 0 }) !== JSON.stringify({ ...project.designSystem, version: 0 });
  function apply() {
    const parsed = designSystemSchema.safeParse(draft);
    if (!parsed.success) { setError('Use a six-digit hex color, such as #405A4A.'); return; }
    if (contrastRatio(draft.accent, '#FFFFFF') < 4.5) { setError('Choose a darker accent so white button labels stay readable.'); return; }
    if (contrastRatio(draft.ink, draft.surface) < 7) { setError('Give text more contrast against the surface so supporting copy stays readable.'); return; }
    updateSystem(parsed.data); setError(''); onApplied();
  }
  const tabs = ['Foundations', 'Components', 'Patterns'];
  return <div className="workspace-page system-page"><div className="page-heading"><div><div className="title-with-icon"><span className="page-icon"><Palette size={19}/></span><h1>Design system</h1></div><p>The foundations that make every direction feel like you.</p></div><span className="version-badge"><span className="tiny-dot"/>Version {project.designSystem.version}</span></div><div className="workspace-tabs" role="tablist" aria-label="Design system sections">{tabs.map((item, index) => <button role="tab" id={`system-tab-${item}`} aria-controls="system-tab-panel" aria-selected={tab === item} tabIndex={tab === item ? 0 : -1} key={item} onClick={() => setTab(item)} onKeyDown={event => { const target = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : -1; if (target >= 0) { event.preventDefault(); setTab(tabs[target]); document.getElementById(`system-tab-${tabs[target]}`)?.focus(); } }}>{item}</button>)}</div>
    <div className="system-layout"><div className="system-settings" role="tabpanel" id="system-tab-panel" aria-labelledby={`system-tab-${tab}`} tabIndex={0}>
      {tab === 'Foundations' && <><section className="setting-section"><div className="setting-title"><h2>Color</h2><p>A small, purposeful palette with a role for every color.</p></div><div className="palette-presets">{[{ name: 'Forest', accent: '#405A4A', surface: '#F5F5EF', ink: '#252D28' }, { name: 'Clay', accent: '#965A42', surface: '#FAF4EE', ink: '#332C28' }, { name: 'Ink', accent: '#3B4964', surface: '#F3F5F8', ink: '#242C3C' }].map(preset => <button key={preset.name} className={draft.accent === preset.accent ? 'palette-preset is-active' : 'palette-preset'} onClick={() => setDraft({ ...draft, accent: preset.accent, surface: preset.surface, ink: preset.ink })}><span style={{ background: preset.accent }}/><span style={{ background: preset.surface }}/><span>{preset.name}</span>{draft.accent === preset.accent && <Check size={12}/>}</button>)}</div>{(['accent', 'surface', 'ink'] as const).map(key => <div className="token-row" key={key}><label htmlFor={`hex-${key}`}><strong>{key === 'ink' ? 'Text' : key[0].toUpperCase() + key.slice(1)}</strong><span>{key === 'accent' ? 'Primary actions and emphasis' : key === 'surface' ? 'The canvas your content sits on' : 'Headings and readable body text'}</span></label><div className="color-input"><input type="color" aria-label={`${key} color picker`} value={/^#[0-9a-f]{6}$/i.test(draft[key]) ? draft[key] : '#000000'} onChange={event => setDraft({ ...draft, [key]: event.target.value.toUpperCase() })}/><input id={`hex-${key}`} aria-label={`${key} hex color`} value={draft[key]} maxLength={7} onChange={event => setDraft({ ...draft, [key]: event.target.value })}/></div></div>)}</section>
      <section className="setting-section"><div className="setting-title"><h2>Typography</h2><p>Set the voice of your generated pages.</p></div><div className="font-choices">{([{ id: 'sans', name: 'Modern sans', sample: 'Aa', description: 'Clear, direct, and approachable.' }, { id: 'serif', name: 'Editorial serif', sample: 'Aa', description: 'Warm, expressive, and considered.' }] as const).map(font => <button className={draft.font === font.id ? `font-choice is-active ${font.id}` : `font-choice ${font.id}`} aria-pressed={draft.font === font.id} key={font.id} onClick={() => setDraft({ ...draft, font: font.id })}><span>{font.sample}</span><strong>{font.name}</strong><small>{font.description}</small>{draft.font === font.id && <Check size={13}/>}</button>)}</div></section>
      <section className="setting-section"><div className="setting-title"><h2>Shape & spacing</h2><p>The details that set your rhythm.</p></div><label className="setting-select"><span><strong>Corner radius</strong><small>A shared shape for buttons and surfaces.</small></span><select value={draft.radius} onChange={event => setDraft({ ...draft, radius: event.target.value as DesignSystem['radius'] })}><option value="square">Square · 0 px</option><option value="soft">Soft · 6 px</option><option value="round">Rounded · 16 px</option></select></label><label className="setting-select"><span><strong>Section spacing</strong><small>Room between ideas on a page.</small></span><select value={draft.density} onChange={event => setDraft({ ...draft, density: event.target.value as DesignSystem['density'] })}><option value="compact">Compact · 48 px</option><option value="comfortable">Comfortable · 72 px</option><option value="spacious">Spacious · 96 px</option></select></label></section></>}
      {tab === 'Components' && <section className="setting-section"><div className="setting-title"><h2>Shared component rules</h2><p>Every registered component resolves these values from your project.</p></div>{[['Buttons', 'Accent color · shared radius'], ['Typography', 'Text color · chosen font family'], ['Sections', 'Surface color · section spacing'], ['Navigation', 'Text color · responsive layout']].map(([name, value]) => <div className="rule-row" key={name}><span>{name}</span><span>{value}</span><ChevronRight size={14}/></div>)}<p className="field-help">Component-level token overrides will be introduced after the foundation controls are reviewed.</p></section>}
      {tab === 'Patterns' && <section className="setting-section"><div className="setting-title"><h2>Page patterns</h2><p>A few steady rules keep every composition coherent.</p></div>{[['Page frame', 'Navigation first. Footer last.'], ['Opening', 'One hero introduces each page.'], ['Content', 'Sections follow a readable, reorderable sequence.'], ['Responsive', 'Columns become a single reading order on smaller screens.']].map(([name, value]) => <div className="pattern-rule" key={name}><Check size={15}/><div><strong>{name}</strong><p>{value}</p></div></div>)}</section>}
    </div><aside className="system-preview"><div className="system-preview-label"><span>Live preview</span><span>Project styles</span></div><div className="token-preview" style={{ background: draft.surface, color: draft.ink, fontFamily: draft.font === 'serif' ? 'Georgia, serif' : 'inherit' }}><span className="preview-brand" style={{ color: draft.accent }}>f.</span><h2>Room for<br/>a good idea.</h2><p>Thoughtful foundations make everything that follows feel connected.</p><button type="button" onClick={() => setTab('Foundations')} style={{ background: draft.accent, borderRadius: draft.radius === 'square' ? 0 : draft.radius === 'soft' ? 6 : 16 }}>Make it yours<ArrowUpRight size={14}/></button><div className="preview-type-scale"><span>Aa</span><div>Good things take shape.<small>A little structure goes a long way.</small></div></div></div><p className="system-scope-note">These rules belong to <strong>{project.name}</strong>. Applying changes updates all {project.directions.length} sample directions.</p></aside></div>
    <div className="system-save-bar"><div>{error ? <span role="alert" className="error-text">{error}</span> : <><span className={changed ? 'tiny-dot warning' : 'tiny-dot'}/>{changed ? 'Unapplied changes' : 'Your foundations are up to date'}</>}</div><div><Button disabled={!changed} onClick={() => { setDraft(project.designSystem); setError(''); }}><RotateCcw size={13}/>Reset</Button><Button variant="primary" disabled={!changed} onClick={apply}>Apply to all directions<Check size={14}/></Button></div></div>
  </div>;
}
