'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowDownToLine, ArrowUpRight, BookOpen, Check, ChevronDown, ChevronRight, CircleHelp, Columns2, Download, FileText, Grid2X2, Image, Layers3, LayoutTemplate, Menu, Monitor, MoreHorizontal, MousePointer2, Palette, PanelLeftClose, PanelLeftOpen, PanelRight, Plus, Redo2, Settings2, Shapes, Smartphone, Tablet, Undo2, X } from 'lucide-react';
import { STORAGE_KEY, useWorkspace } from '@clayface/editor';
import { getComponent } from '@clayface/registry';
import { cn } from '@/lib/utils';
import { Button, ClayfaceMark, downloadJson, EmptyState, IconButton, ModalDialog, NavigationDrawer } from './ui';
import { Canvas } from './canvas';
import { Inspector } from './inspector';
import { Directions, NewDirectionDialog } from './directions';
import { DesignSystemWorkspace } from './design-system';
import { ComponentCatalog, Assets } from './catalog';
import { AccountSettingsModal } from './account-security';

type View = 'editor' | 'directions' | 'design-system' | 'components' | 'assets';
const navigation = [{ id: 'editor', label: 'Editor', icon: MousePointer2 }, { id: 'directions', label: 'Directions', icon: Layers3 }, { id: 'design-system', label: 'Design system', icon: Palette }, { id: 'components', label: 'Components', icon: Shapes }, { id: 'assets', label: 'Assets', icon: Image }] as const;
const nodeIcons = { navigation: Columns2, hero: LayoutTemplate, features: Grid2X2, statement: FileText, pricing: Columns2, contact: FileText, cta: ArrowUpRight, footer: Columns2, 'layout.page': FileText };

export function Workspace() {
  const state = useWorkspace();
  const [view, setView] = useState<View>('editor');
  const [workspaceMode, setWorkspaceMode] = useState<'pages' | 'build'>('pages');
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [inspectorOpen, setInspectorOpen] = useState(false);
  const [viewport, setViewport] = useState(1080);
  const [zoom, setZoom] = useState<number | 'fit'>('fit');
  const [newDirection, setNewDirection] = useState(false);
  const [projectMenu, setProjectMenu] = useState(false);
  const [help, setHelp] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);
  const [toast, setToast] = useState('');
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const direction = state.project.directions.find(item => item.id === state.directionId) ?? state.project.directions[0];
  const page = direction?.document.pages.find(item => item.route === state.pageRoute) ?? direction?.document.pages[0];

  function openAccount() { if (state.saveStatus !== 'saved') { notify('Wait for your changes to save before opening account settings.'); return; } setAccountOpen(true); }
  function navigate(next: View) { setView(next); setWorkspaceMode(next === 'editor' || next === 'directions' ? 'pages' : 'build'); setMobileNav(false); window.history.replaceState(null, '', next === 'editor' ? '/dashboard' : `/dashboard#${next}`); }
  function notify(message: string) { setToast(message); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 3600); }

  useEffect(() => {
    state.hydrate();
    const hash = window.location.hash.slice(1);
    if (navigation.some(item => item.id === hash)) setView(hash as View);
    const onHash = () => { const hash = window.location.hash.slice(1); setView(navigation.some(item => item.id === hash) ? hash as View : 'editor'); };
    const onKey = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement;
      if (target.matches('input,textarea,select') || target.isContentEditable) return;
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); if (event.shiftKey) useWorkspace.getState().redo(); else useWorkspace.getState().undo(); }
      if (event.key === 'Escape') { setMobileNav(false); setInspectorOpen(false); }
    };
    window.addEventListener('hashchange', onHash); window.addEventListener('keydown', onKey);
    return () => { window.removeEventListener('hashchange', onHash); window.removeEventListener('keydown', onKey); if (toastTimer.current) clearTimeout(toastTimer.current); };
  }, [state.hydrate]);

  return <div className={cn('app', sidebarCollapsed && 'sidebar-collapsed', mobileNav && 'mobile-nav-open', inspectorOpen && 'inspector-open')}>
    <a className="skip-link" href="#workspace-main">Skip to workspace</a>
    <header className="topbar"><div className="brand-area"><IconButton label="Open navigation" className="mobile-nav-trigger" onClick={() => setMobileNav(true)}><Menu size={18}/></IconButton><a href="/dashboard" className="brand" aria-label="Clayface workspace"><ClayfaceMark/><span>clayface</span></a><span className="brand-beta">early access</span></div><div className="topbar-project"><span className="topbar-divider"/><span>{state.project.name}</span><ChevronRight size={13}/><span>{navigation.find(item => item.id === view)?.label}</span></div><div className="topbar-actions"><span role="status" className={cn('save-status', state.saveStatus === 'error' && 'error-text')}>{state.saveStatus === 'saved' ? <Check size={13}/> : <span className="tiny-dot warning"/>}<span className="save-label-full">{!state.hydrated ? 'Opening…' : state.saveStatus === 'saved' ? 'Saved to your account' : state.saveStatus === 'saving' ? 'Saving…' : 'Not saved'}</span><span className="save-label-compact">{!state.hydrated ? 'Opening…' : state.saveStatus === 'saved' ? 'Saved' : state.saveStatus === 'saving' ? 'Saving…' : 'Not saved'}</span></span><IconButton label="Workspace help" onClick={() => setHelp(true)}><CircleHelp size={16}/></IconButton><button className="account-avatar" aria-label="Account settings" onClick={() => openAccount()}>Y</button></div></header>
    <NavigationDrawer open={mobileNav} onClose={() => setMobileNav(false)}><aside className="sidebar" aria-label="Project navigation"><div className="project-identity"><span className="project-avatar">{state.project.name.charAt(0).toUpperCase()}</span><div><strong>{state.project.name}</strong><span>Marketing website</span></div><IconButton label="Project options" onClick={() => setProjectMenu(true)}><MoreHorizontal size={17}/></IconButton><IconButton label="Close navigation" className="mobile-nav-close" onClick={() => setMobileNav(false)}><X size={17}/></IconButton></div>
      <div className="workspace-mode-tabs" role="tablist" aria-label="Workspace areas"><button role="tab" aria-selected={workspaceMode === 'pages'} className={workspaceMode === 'pages' ? 'is-active' : ''} onClick={() => navigate('editor')}><MousePointer2 size={15}/>Pages</button><button role="tab" aria-selected={workspaceMode === 'build'} className={workspaceMode === 'build' ? 'is-active' : ''} onClick={() => navigate('design-system')}><Palette size={15}/>Build</button></div><nav className="main-navigation">{navigation.filter(item => workspaceMode === 'pages' ? item.id === 'editor' || item.id === 'directions' : item.id === 'design-system' || item.id === 'components' || item.id === 'assets').map(item => <button key={item.id} className={cn('nav-item', view === item.id && 'is-active')} aria-current={view === item.id ? 'page' : undefined} title={sidebarCollapsed ? item.label : undefined} onClick={() => navigate(item.id)}><item.icon size={16}/><span>{item.label}</span>{item.id === 'directions' && <small>{state.project.directions.length}<span>/3</span></small>}</button>)}</nav>
      {view === 'editor' && <div className="sidebar-tree"><div className="sidebar-label"><span>Pages</span><span>{direction?.document.pages.length ?? 0}</span></div><nav className="page-navigation" aria-label="Pages">{direction?.document.pages.map(item => <button key={item.id} className={cn('page-item', page?.id === item.id && 'is-active')} onClick={() => { state.selectPage(item.route); setMobileNav(false); }}><FileText size={14}/><span>{item.name}</span>{item.route === '/' && <span className="home-indicator">/</span>}</button>)}</nav>{page && <><div className="sidebar-label structure-label"><span>On this page</span><Layers3 size={12}/></div><nav className="section-tree" aria-label="Page sections">{page.root.children.map(node => { const Icon = nodeIcons[node.componentId]; return <button key={node.id} className={cn('tree-item', state.selectedId === node.id && 'is-active')} onClick={() => { state.selectNode(node.id); setMobileNav(false); }}><span className="tree-line"/><Icon size={13}/><span>{getComponent(node.componentId).name}</span>{state.selectedId === node.id && <span className="selection-dot"/>}</button>; })}</nav></>}</div>}
      {view !== 'editor' && <div className="sidebar-context"><span className="sidebar-label">Project foundations</span><div className="sidebar-system-colors"><i style={{ background: state.project.designSystem.accent }}/><i style={{ background: state.project.designSystem.surface }}/><i style={{ background: state.project.designSystem.ink }}/></div><strong>{state.project.designSystem.name}</strong><p>Shared by all your directions.</p><button onClick={() => navigate('design-system')}>View foundations<ArrowUpRight size={12}/></button></div>}
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => openAccount()}><Settings2 size={16}/><span>Account settings</span></button><div className="sidebar-footer"><button className="local-label" onClick={() => openAccount()}><span className="tiny-dot"/><span>Your account</span></button><IconButton label={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'} className="collapse-sidebar" onClick={() => setSidebarCollapsed(!sidebarCollapsed)}>{sidebarCollapsed ? <PanelLeftOpen size={16}/> : <PanelLeftClose size={16}/>}</IconButton></div></div>
    </aside></NavigationDrawer>
    <main id="workspace-main" className={cn('workspace-main', view !== 'editor' && 'full-workspace')} tabIndex={-1}>
      <div className="workspace-toolbar"><div className="toolbar-location">{view === 'editor' ? <><span className="file-tab"><FileText size={14}/>{page?.name ?? 'No page'}<span className="tiny-dot"/></span><span className="toolbar-slash">/</span><label className="direction-select"><Layers3 size={13}/><select aria-label="Active direction" value={direction?.id ?? ''} onChange={event => state.selectDirection(event.target.value)}>{state.project.directions.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown size={12}/></label></> : <span className="toolbar-title">{state.project.name}<ChevronRight size={12}/>{navigation.find(item => item.id === view)?.label}</span>}</div><div className="toolbar-actions"><div className="history-controls"><IconButton label="Undo" disabled={!state.history.length} onClick={state.undo}><Undo2 size={15}/></IconButton><IconButton label="Redo" disabled={!state.future.length} onClick={state.redo}><Redo2 size={15}/></IconButton></div>{direction && <Link className="button button-secondary preview-button" href="/dashboard/preview" onClick={event => { if (state.saveStatus !== 'saved') { event.preventDefault(); notify('Wait for your changes to save before opening the preview.'); } }}><ArrowUpRight size={14}/>Preview</Link>}<Button className="export-button" disabled title="Next.js export will be available in the export milestone."><Download size={13}/>Export</Button>{view === 'editor' && <IconButton label="Toggle inspector" className="inspector-trigger" aria-pressed={inspectorOpen} onClick={() => setInspectorOpen(!inspectorOpen)}><PanelRight size={16}/></IconButton>}</div></div>
      {state.storageError && <div className="error-banner" role="alert"><span>{state.storageError}</span><Button onClick={() => { try { downloadJson(localStorage.getItem(STORAGE_KEY) ?? '{}', 'clayface-recovery.json'); } catch { notify('Browser storage is unavailable.'); } }}>Download backup</Button><Button onClick={state.recover}>Use sample project</Button></div>}
      {state.error && !state.storageError && <div className="error-banner" role="alert"><span>{state.error}</span>{state.saveStatus === 'error' && <Button onClick={state.save}>Retry save</Button>}<IconButton label="Dismiss error" onClick={state.clearError}><X size={15}/></IconButton></div>}
      {!state.hydrated ? <div className="workspace-skeleton" role="status" aria-label="Loading workspace"><div/><div/><div/></div> : view === 'editor' ? <div className="editor-layout"><div className="canvas-workspace"><div className="canvas-toolbar"><div className="canvas-context"><span className="tiny-dot"/>Editing<span className="canvas-context-description">Select a section to make it yours</span></div><div className="viewport-controls" aria-label="Canvas viewport">{[{ width: 1080, label: 'Desktop viewport', Icon: Monitor }, { width: 768, label: 'Tablet viewport', Icon: Tablet }, { width: 390, label: 'Mobile viewport', Icon: Smartphone }].map(({ width, label, Icon }) => <IconButton key={width} label={label} aria-pressed={viewport === width} className={viewport === width ? 'is-active' : ''} onClick={() => { setViewport(width); setZoom('fit'); }}><Icon size={15}/></IconButton>)}</div></div>{page ? <Canvas key={page.id} page={page} system={state.project.designSystem} selectedId={state.selectedId} onSelect={id => state.selectNode(id)} viewport={viewport} zoom={zoom}/> : <EmptyState title="Let’s find your first direction." description="Create a direction to start exploring your project."><Button variant="primary" onClick={() => setNewDirection(true)}><Plus size={14}/>Add a direction</Button></EmptyState>}<div className="canvas-statusbar"><span><MousePointer2 size={12}/>{state.selectedId ? 'Section selected' : 'Click a section to select'}</span><div><span className="canvas-size">{viewport} × auto</span><label className="zoom-select"><select aria-label="Canvas zoom" value={zoom} onChange={event => setZoom(event.target.value === 'fit' ? 'fit' : Number(event.target.value))}><option value="fit">Fit</option><option value="50">50%</option><option value="75">75%</option><option value="100">100%</option></select><ChevronDown size={11}/></label></div></div></div><Inspector onSystem={() => navigate('design-system')} onClose={() => setInspectorOpen(false)}/></div> : <div className="workspace-content">{view === 'directions' && <Directions onOpen={() => navigate('editor')} onNew={() => setNewDirection(true)}/>} {view === 'design-system' && <DesignSystemWorkspace onApplied={() => notify('Design system applied to all directions.')}/>} {view === 'components' && <ComponentCatalog/>}{view === 'assets' && <Assets/>}</div>}
    </main>
    <NewDirectionDialog open={newDirection} onClose={() => setNewDirection(false)} onCreated={() => { navigate('editor'); notify('Your direction is ready to explore.'); }}/>
    <ModalDialog open={projectMenu} onClose={() => setProjectMenu(false)} title={state.project.name} description={state.project.brief}><div className="project-menu-actions"><Button onClick={() => { setProjectMenu(false); openAccount(); }}><Settings2 size={16}/>Account settings<ChevronRight size={14}/></Button><Button onClick={() => { downloadJson(state.project, `${state.project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-clayface.json`); setProjectMenu(false); notify('Workspace document downloaded.'); }}><ArrowDownToLine size={16}/>Download workspace JSON<ChevronRight size={14}/></Button><Button onClick={() => { setProjectMenu(false); navigate('directions'); }}><Layers3 size={16}/>Manage directions<ChevronRight size={14}/></Button></div><p className="field-help">This JSON is a backup of your workspace. Next.js code export is not connected yet.</p></ModalDialog>
    <ModalDialog open={help} onClose={() => setHelp(false)} title="A little help finding your way." description="Clayface gives your project a shared design language, then lets you explore different ways to put it together."><div className="help-steps"><div><MousePointer2 size={18}/><span><strong>Select a section</strong><p>Click the canvas or page tree. Its controls appear in the inspector.</p></span></div><div><Layers3 size={18}/><span><strong>Explore a direction</strong><p>Switch between compositions, or add one in Directions. There are three slots.</p></span></div><div><Palette size={18}/><span><strong>Make the system yours</strong><p>Preview color, type, and spacing changes before applying them to every direction.</p></span></div><div><BookOpen size={18}/><span><strong>Keep your work</strong><p>Edits save to your account. Download a JSON backup from Project options.</p></span></div></div><div className="keyboard-hint"><span>Undo / redo outside text fields</span><kbd>Ctrl / ⌘ Z</kbd><kbd>⇧ Z</kbd></div></ModalDialog>
    <AccountSettingsModal open={accountOpen} onClose={() => setAccountOpen(false)} />
    {toast && <div className="toast" role="status"><Check size={15}/>{toast}<IconButton label="Dismiss notification" onClick={() => setToast('')}><X size={13}/></IconButton></div>}
  </div>;
}
